### PR TITLE
Upgraded vendored pystac to v1.3.0

### LINKED ISSUE #114: Upgrade to latest pystac version
Firstly: this is a great plugin, thank you. I've wanted a QGIS plugin for STAC for ages, and this is absolutely brilliant! Now on to the actual issue:

The version of the pystac library that is included with this plugin is slightly out of date (understandably), but that means it doesn't include [this](https://github.com/stac-utils/pystac/pull/697) bugfix. Without that PR, pystac fails to list the collections for any of my STAC API servers.

I'll submit a PR shortly to upgrade the included pystac.

### PR DESCRIPTION
**Pull request by robintw**
Fixes #114 by upgrading to the latest release of pystac.

### CODE REVIEW

**Comment by timlinux** [comment]
Nice, thanks for this @robintw !

**Comment by Samweli** [comment]
Hi @robintw, many thanks for the PR, I checked the pystac_client lib which the plugin depends on and the library still uses pystac version 1.2.0, there might be some break updating the pystac lib at the moment.

**Comment by Samweli** [comment]
Do you have any issue using the plugin with the pystac version 1.2.0? We are also planning to update the pystac-client library soon to version 0.3.2.

**Comment by Samweli** [comment]
@robintw merging this due to the inclusion of a pystac fix here https://github.com/stac-utils/pystac/pull/697. Many thanks!

**Pull request merged**
